"use client";

import { createContext, useContext, useState, useEffect, ReactNode } from "react";
import { useSession } from "next-auth/react";

export type Language = "fr" | "en" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => Promise<void>;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Common
    "dashboard": "Tableau de bord",
    "home": "Accueil",
    "workspace": "Espace de travail",
    "settings": "Paramètres",
    "profile": "Profil",
    "logout": "Déconnexion",
    "login": "Connexion",
    "save": "Enregistrer",
    "cancel": "Annuler",
    "delete": "Supprimer",
    "edit": "Modifier",
    "add": "Ajouter",
    "search": "Rechercher",
    "loading": "Chargement...",
    "error": "Erreur",
    "success": "Succès",
    "confirm": "Confirmer",
    "close": "Fermer",
    "back": "Retour",
    "next": "Suivant",
    "previous": "Précédent",
    "submit": "Soumettre",
    "reset": "Réinitialiser",
    "clear": "Effacer",
    "view": "Voir",
    "download": "Télécharger",
    "upload": "Télécharger",
    "refresh": "Actualiser",
    "filter": "Filtrer",
    "export": "Exporter",
    "import": "Importer",
    "print": "Imprimer",
    "copy": "Copier",
    "select": "Sélectionner",
    "select_all": "Tout sélectionner",
    "deselect_all": "Tout désélectionner",
    "yes": "Oui",
    "no": "Non",
    "or": "ou",
    "and": "et",
    "optional": "optionnel",
    "required": "requis",
    "actions": "Actions",
    "details": "Détails",
    "description": "Description",
    "date": "Date",
    "time": "Heure",
    "status": "Statut",
    "type": "Type",
    "name": "Nom",
    "title": "Titre",
    "message": "Message",
    "comment": "Commentaire",
    "notes": "Notes",
    "created_at": "Créé le",
    "updated_at": "Mis à jour le",
    "created_by": "Créé par",
    "all": "Tous",
    "none": "Aucun",
    "today": "Aujourd'hui",
    "yesterday": "Hier",
    "this_week": "Cette semaine",
    "this_month": "Ce mois",
    "this_year": "Cette année",
    
    // Navigation / Sidebar
    "employees": "Employés",
    "attendance": "Pointage",
    "leaves": "Congés",
    "documents": "Documents",
    "contracts": "Contrats",
    "ai_assistant": "Assistant IA",
    "hr": "Ressources humaines",
    "notifications": "Notifications",
    "my_documents": "Mes documents",
    "leave_requests": "Demandes de congé",
    "leave_management": "Gestion des congés",
    "notification_center": "Centre de notifications",
    "user_management": "Gestion utilisateurs",
    "role_management": "Gestion des rôles",
    "help": "Assistance",
    "audit_logs": "Journal d'audit",
    "cookie_settings": "Paramètres cookies",
    "administration": "Administration",
    "profile_validation": "Validation profils",
    "login_history": "Historique des connexions",
    "public_holidays": "Jours fériés",
    "manage_holidays_desc": "Gérez les jours fériés nationaux et religieux",
    "add_holiday": "Ajouter un jour férié",
    "edit_holiday": "Modifier le jour férié",
    "holiday_name": "Nom du jour férié",
    "holiday_name_placeholder": "Ex: Fête de l'indépendance",
    "holiday_description_placeholder": "Description ou notes...",
    "national": "National",
    "religious": "Religieux",
    "national_holidays": "Jours nationaux",
    "religious_holidays": "Jours religieux",
    "total_holidays": "Total jours fériés",
    "paid_holidays": "Jours payés",
    "paid": "Payé",
    "unpaid": "Non payé",
    "paid_holiday": "Jour payé",
    "paid_holiday_desc": "Ce jour férié est rémunéré",
    "unpaid_holiday_desc": "Ce jour férié n'est pas rémunéré",
    "fixed_date": "Date fixe chaque année",
    "fixed_date_desc": "La date ne change pas d'une année à l'autre",
    "variable_date_desc": "La date change chaque année (ex: fêtes religieuses)",
    "date_changes": "Date variable",
    "variable_date": "Date variable",
    "fixed_short": "Fixe",
    "variable_short": "Variable",
    "day_name": "Jour",
    "holidays_list": "Liste des jours fériés",
    "no_holidays": "Aucun jour férié",
    "no_holidays_desc": "Aucun jour férié configuré pour cette année",
    "duplicate_year": "Dupliquer l'année",
    "duplicate_holidays": "Dupliquer les jours fériés",
    "duplicate_holidays_desc": "Copiez les jours fériés récurrents d'une année vers une autre. Les jours religieux seront copiés avec un rappel de vérifier la date.",
    "from_year": "Année source",
    "to_year": "Année cible",
    "duplicate": "Dupliquer",
    "duplicate_warning": "Les jours fériés religieux ont des dates variables. Pensez à vérifier et ajuster les dates après la duplication.",
    "confirm_delete_holiday_desc": "Êtes-vous sûr de vouloir supprimer ce jour férié ? Cette action est irréversible.",
    "holiday_created_success": "Jour férié créé avec succès",
    "holiday_updated_success": "Jour férié mis à jour avec succès",
    "holiday_deleted_success": "Jour férié supprimé avec succès",
    "error_loading_holidays": "Erreur lors du chargement des jours fériés",
    "religious_holiday_warning_title": "Jour religieux à date variable",
    "religious_holiday_warning_desc": "La date de ce jour férié religieux change chaque année. Pensez à la mettre à jour annuellement.",
    "list": "Liste",
    "my_profile": "Mon profil",
    "my_attendance": "Mon pointage",
    "my_leaves": "Mes congés",
    "my_contracts": "Mes contrats",
    "admin": "Admin",
    "super_admin": "Super Admin",
    
    // Settings
    "general": "Général",
    "security": "Sécurité",
    "appearance": "Apparence",
    "devices": "Appareils",
    "language": "Langue",
    "theme": "Thème",
    "dark_mode": "Mode sombre",
    "light_mode": "Mode clair",
    "system": "Système",
    "notifications_settings": "Paramètres des notifications",
    "email_notifications": "Notifications par email",
    "push_notifications": "Notifications push",
    "privacy": "Confidentialité",
    
    // User / Profile
    "first_name": "Prénom",
    "last_name": "Nom",
    "email": "Email",
    "phone": "Téléphone",
    "password": "Mot de passe",
    "change_password": "Changer le mot de passe",
    "current_password": "Mot de passe actuel",
    "new_password": "Nouveau mot de passe",
    "confirm_password": "Confirmer le mot de passe",
    "address": "Adresse",
    "city": "Ville",
    "country": "Pays",
    "postal_code": "Code postal",
    "date_of_birth": "Date de naissance",
    "gender": "Genre",
    "male": "Homme",
    "female": "Femme",
    "other": "Autre",
    "department": "Département",
    "position": "Poste",
    "hire_date": "Date d'embauche",
    "employee_id": "Matricule",
    "manager": "Manager",
    "team": "Équipe",
    "avatar": "Photo de profil",
    "change_avatar": "Changer la photo",
    "role": "Rôle",
    "user": "Utilisateur",
    
    // Status
    "active": "Actif",
    "inactive": "Inactif",
    "pending": "En attente",
    "approved": "Approuvé",
    "rejected": "Rejeté",
    "suspended": "Suspendu",
    "archived": "Archivé",
    "draft": "Brouillon",
    "sent": "Envoyé",
    "viewed": "Consulté",
    "signed": "Signé",
    "cancelled": "Annulé",
    "completed": "Terminé",
    "in_progress": "En cours",
    "expired": "Expiré",
    "valid": "Valide",
    "invalid": "Invalide",
    "online": "En ligne",
    "offline": "Hors ligne",
    
    // Pointage / Attendance
    "check_in": "Pointer l'entrée",
    "check_out": "Pointer la sortie",
    "checked_in": "Entrée pointée",
    "checked_out": "Sortie pointée",
    "check_in_time": "Heure d'entrée",
    "check_out_time": "Heure de sortie",
    "working_hours": "Heures travaillées",
    "overtime": "Heures supplémentaires",
    "late": "Retard",
    "early_departure": "Départ anticipé",
    "absence": "Absence",
    "present": "Présent",
    "absent": "Absent",
    "on_leave": "En congé",
    "remote": "Télétravail",
    "business_trip": "Déplacement",
    "attendance_history": "Historique de pointage",
    "today_attendance": "Pointage du jour",
    "monthly_summary": "Résumé mensuel",
    "weekly_summary": "Résumé hebdomadaire",
    "face_recognition": "Reconnaissance faciale",
    "manual_entry": "Saisie manuelle",
    "location": "Emplacement",
    "device": "Appareil",
    "already_checked_in": "Vous avez déjà pointé votre entrée aujourd'hui",
    "already_checked_out": "Vous avez déjà pointé votre sortie aujourd'hui",
    "must_check_in_first": "Vous devez d'abord pointer votre entrée",
    "please_wait": "Veuillez patienter quelques secondes",
    "pointage_success": "Pointage enregistré avec succès",
    "pointage_error": "Erreur lors du pointage",
    
    // Congés / Leaves
    "leave_request": "Demande de congé",
    "leave_type": "Type de congé",
    "start_date": "Date de début",
    "end_date": "Date de fin",
    "duration": "Durée",
    "days": "jours",
    "half_day": "Demi-journée",
    "full_day": "Journée complète",
    "reason": "Motif",
    "balance": "Solde",
    "remaining_days": "Jours restants",
    "used_days": "Jours utilisés",
    "annual_leave": "Congé annuel",
    "sick_leave": "Congé maladie",
    "unpaid_leave": "Congé sans solde",
    "maternity_leave": "Congé maternité",
    "paternity_leave": "Congé paternité",
    "bereavement_leave": "Congé décès",
    "special_leave": "Congé spécial",
    "pending_requests": "Demandes en attente",
    "approved_requests": "Demandes approuvées",
    "rejected_requests": "Demandes refusées",
    "approve": "Approuver",
    "reject": "Rejeter",
    "request_leave": "Demander un congé",
    "cancel_request": "Annuler la demande",
    "leave_calendar": "Calendrier des congés",
    "team_calendar": "Calendrier d'équipe",
    
    // Documents / Contracts
    "document": "Document",
    "contract": "Contrat",
    "file": "Fichier",
    "files": "Fichiers",
    "upload_file": "Télécharger un fichier",
    "download_file": "Télécharger le fichier",
    "file_name": "Nom du fichier",
    "file_type": "Type de fichier",
    "file_size": "Taille du fichier",
    "upload_date": "Date de téléchargement",
    "contract_type": "Type de contrat",
    "cdi": "CDI",
    "cdd": "CDD",
    "stage": "Stage",
    "freelance": "Freelance",
    "sign_contract": "Signer le contrat",
    "signature": "Signature",
    "draw_signature": "Dessinez votre signature",
    "clear_signature": "Effacer la signature",
    "signed_on": "Signé le",
    "sent_for_signature": "Envoyé pour signature",
    "pending_signature": "Signature en attente",
    "contract_signed": "Contrat signé",
    "contract_archived": "Contrat archivé",
    "view_document": "Voir le document",
    "download_signed": "Télécharger la version signée",
    "pdf_preview": "Aperçu PDF",
    
    // Notifications
    "mark_as_read": "Marquer comme lu",
    "mark_all_read": "Tout marquer comme lu",
    "unread": "Non lu",
    "read": "Lu",
    "new_notification": "Nouvelle notification",
    "no_notifications": "Aucune notification",
    "notification_settings": "Paramètres de notification",
    "email_me_when": "M'envoyer un email quand",
    "push_notify_when": "Notification push quand",
    "high_priority": "Priorité haute",
    "normal_priority": "Priorité normale",
    "low_priority": "Priorité basse",
    
    // Auth
    "sign_in": "Se connecter",
    "sign_up": "S'inscrire",
    "sign_out": "Se déconnecter",
    "forgot_password": "Mot de passe oublié ?",
    "reset_password": "Réinitialiser le mot de passe",
    "remember_me": "Se souvenir de moi",
    "verification_code": "Code de vérification",
    "enter_code": "Entrez le code",
    "send_code": "Envoyer le code",
    "resend_code": "Renvoyer le code",
    "verify": "Vérifier",
    "otp_sent": "Code envoyé à votre email",
    "invalid_credentials": "Identifiants invalides",
    "account_locked": "Compte verrouillé",
    "account_suspended": "Compte suspendu",
    "session_expired": "Session expirée",
    "two_factor": "Authentification à deux facteurs",
    "enable_2fa": "Activer 2FA",
    "disable_2fa": "Désactiver 2FA",
    
    // Errors
    "error_occurred": "Une erreur s'est produite",
    "try_again": "Réessayer",
    "page_not_found": "Page non trouvée",
    "access_denied": "Accès refusé",
    "unauthorized": "Non autorisé",
    "forbidden": "Interdit",
    "internal_error": "Erreur interne du serveur",
    "network_error": "Erreur réseau",
    "timeout_error": "Délai d'attente dépassé",
    "validation_error": "Erreur de validation",
    "required_field": "Ce champ est requis",
    "invalid_email": "Email invalide",
    "invalid_phone": "Numéro de téléphone invalide",
    "password_too_short": "Mot de passe trop court",
    "passwords_dont_match": "Les mots de passe ne correspondent pas",
    "invalid_date": "Date invalide",
    "file_too_large": "Fichier trop volumineux",
    "invalid_file_type": "Type de fichier invalide",
    
    // Success messages
    "saved_successfully": "Enregistré avec succès",
    "deleted_successfully": "Supprimé avec succès",
    "updated_successfully": "Mis à jour avec succès",
    "created_successfully": "Créé avec succès",
    "submitted_successfully": "Soumis avec succès",
    "uploaded_successfully": "Téléchargé avec succès",
    "sent_successfully": "Envoyé avec succès",
    "copied_to_clipboard": "Copié dans le presse-papiers",
    
    // Confirmations
    "confirm_delete": "Êtes-vous sûr de vouloir supprimer ?",
    "confirm_cancel": "Êtes-vous sûr de vouloir annuler ?",
    "confirm_logout": "Êtes-vous sûr de vouloir vous déconnecter ?",
    "confirm_action": "Êtes-vous sûr de vouloir continuer ?",
    "unsaved_changes": "Vous avez des modifications non enregistrées",
    
    // Messages
    "welcome": "Bienvenue",
    "goodbye": "Au revoir",
    "no_data": "Aucune donnée disponible",
    "no_results": "Aucun résultat trouvé",
    "loading_data": "Chargement des données...",
    "processing": "Traitement en cours...",
    "please_wait_processing": "Veuillez patienter, traitement en cours...",
    
    // Dashboard
    "total_employees": "Total employés",
    "present_today": "Présents aujourd'hui",
    "on_leave_today": "En congé aujourd'hui",
    "pending_validations": "Validations en attente",
    "recent_activities": "Activités récentes",
    "quick_actions": "Actions rapides",
    "statistics": "Statistiques",
    "overview": "Vue d'ensemble",
    "analytics": "Analytiques",
    "reports": "Rapports",
    
    // Help
    "faq": "FAQ",
    "contact_support": "Contacter le support",
    "send_message": "Envoyer un message",
    "need_help": "Besoin d'aide ?",
  },
  en: {
    // Common
    "dashboard": "Dashboard",
    "home": "Home",
    "workspace": "Workspace",
    "settings": "Settings",
    "profile": "Profile",
    "logout": "Logout",
    "login": "Login",
    "save": "Save",
    "cancel": "Cancel",
    "delete": "Delete",
    "edit": "Edit",
    "add": "Add",
    "search": "Search",
    "loading": "Loading...",
    "error": "Error",
    "success": "Success",
    "confirm": "Confirm",
    "close": "Close",
    "back": "Back",
    "next": "Next",
    "previous": "Previous",
    "submit": "Submit",
    "reset": "Reset",
    "clear": "Clear",
    "view": "View",
    "download": "Download",
    "upload": "Upload",
    "refresh": "Refresh",
    "filter": "Filter",
    "export": "Export",
    "import": "Import",
    "print": "Print",
    "copy": "Copy",
    "select": "Select",
    "select_all": "Select all",
    "deselect_all": "Deselect all",
    "yes": "Yes",
    "no": "No",
    "or": "or",
    "and": "and",
    "optional": "optional",
    "required": "required",
    "actions": "Actions",
    "details": "Details",
    "description": "Description",
    "date": "Date",
    "time": "Time",
    "status": "Status",
    "type": "Type",
    "name": "Name",
    "title": "Title",
    "message": "Message",
    "comment": "Comment",
    "notes": "Notes",
    "created_at": "Created at",
    "updated_at": "Updated at",
    "created_by": "Created by",
    "all": "All",
    "none": "None",
    "today": "Today",
    "yesterday": "Yesterday",
    "this_week": "This week",
    "this_month": "This month",
    "this_year": "This year",
    
    // Navigation / Sidebar
    "employees": "Employees",
    "attendance": "Attendance",
    "leaves": "Leaves",
    "documents": "Documents",
    "contracts": "Contracts",
    "ai_assistant": "AI Assistant",
    "hr": "Human Resources",
    "notifications": "Notifications",
    "my_documents": "My documents",
    "leave_requests": "Leave requests",
    "leave_management": "Leave management",
    "notification_center": "Notification center",
    "user_management": "User management",
    "role_management": "Role management",
    "help": "Help",
    "audit_logs": "Audit Logs",
    "cookie_settings": "Cookie Settings",
    "administration": "Administration",
    "profile_validation": "Profile Validation",
    "login_history": "Login History",
    "public_holidays": "Public Holidays",
    "manage_holidays_desc": "Manage national and religious public holidays",
    "add_holiday": "Add Holiday",
    "edit_holiday": "Edit Holiday",
    "holiday_name": "Holiday Name",
    "holiday_name_placeholder": "E.g.: Independence Day",
    "holiday_description_placeholder": "Description or notes...",
    "national": "National",
    "religious": "Religious",
    "national_holidays": "National holidays",
    "religious_holidays": "Religious holidays",
    "total_holidays": "Total holidays",
    "paid_holidays": "Paid holidays",
    "paid": "Paid",
    "unpaid": "Unpaid",
    "paid_holiday": "Paid holiday",
    "paid_holiday_desc": "This holiday is paid",
    "unpaid_holiday_desc": "This holiday is not paid",
    "fixed_date": "Fixed date each year",
    "fixed_date_desc": "The date stays the same every year",
    "variable_date_desc": "The date changes every year (e.g., religious holidays)",
    "date_changes": "Variable date",
    "variable_date": "Variable date",
    "fixed_short": "Fixed",
    "variable_short": "Variable",
    "day_name": "Day",
    "holidays_list": "Holidays list",
    "no_holidays": "No holidays",
    "no_holidays_desc": "No holidays configured for this year",
    "duplicate_year": "Duplicate year",
    "duplicate_holidays": "Duplicate holidays",
    "duplicate_holidays_desc": "Copy recurring holidays from one year to another. Religious holidays will be copied with a reminder to verify the date.",
    "from_year": "Source year",
    "to_year": "Target year",
    "duplicate": "Duplicate",
    "duplicate_warning": "Religious holidays have variable dates. Remember to verify and adjust dates after duplication.",
    "confirm_delete_holiday_desc": "Are you sure you want to delete this holiday? This action cannot be undone.",
    "holiday_created_success": "Holiday created successfully",
    "holiday_updated_success": "Holiday updated successfully",
    "holiday_deleted_success": "Holiday deleted successfully",
    "error_loading_holidays": "Error loading holidays",
    "religious_holiday_warning_title": "Religious holiday with variable date",
    "religious_holiday_warning_desc": "The date of this religious holiday changes every year. Remember to update it annually.",
    "list": "List",
    "my_profile": "My profile",
    "my_attendance": "My attendance",
    "my_leaves": "My leaves",
    "my_contracts": "My contracts",
    "admin": "Admin",
    "super_admin": "Super Admin",
    
    // Settings
    "general": "General",
    "security": "Security",
    "appearance": "Appearance",
    "devices": "Devices",
    "language": "Language",
    "theme": "Theme",
    "dark_mode": "Dark mode",
    "light_mode": "Light mode",
    "system": "System",
    "notifications_settings": "Notification settings",
    "email_notifications": "Email notifications",
    "push_notifications": "Push notifications",
    "privacy": "Privacy",
    
    // User / Profile
    "first_name": "First name",
    "last_name": "Last name",
    "email": "Email",
    "phone": "Phone",
    "password": "Password",
    "change_password": "Change password",
    "current_password": "Current password",
    "new_password": "New password",
    "confirm_password": "Confirm password",
    "address": "Address",
    "city": "City",
    "country": "Country",
    "postal_code": "Postal code",
    "date_of_birth": "Date of birth",
    "gender": "Gender",
    "male": "Male",
    "female": "Female",
    "other": "Other",
    "department": "Department",
    "position": "Position",
    "hire_date": "Hire date",
    "employee_id": "Employee ID",
    "manager": "Manager",
    "team": "Team",
    "avatar": "Profile picture",
    "change_avatar": "Change picture",
    "role": "Role",
    "user": "User",
    
    // Status
    "active": "Active",
    "inactive": "Inactive",
    "pending": "Pending",
    "approved": "Approved",
    "rejected": "Rejected",
    "suspended": "Suspended",
    "archived": "Archived",
    "draft": "Draft",
    "sent": "Sent",
    "viewed": "Viewed",
    "signed": "Signed",
    "cancelled": "Cancelled",
    "completed": "Completed",
    "in_progress": "In progress",
    "expired": "Expired",
    "valid": "Valid",
    "invalid": "Invalid",
    "online": "Online",
    "offline": "Offline",
    
    // Pointage / Attendance
    "check_in": "Check in",
    "check_out": "Check out",
    "checked_in": "Checked in",
    "checked_out": "Checked out",
    "check_in_time": "Check-in time",
    "check_out_time": "Check-out time",
    "working_hours": "Working hours",
    "overtime": "Overtime",
    "late": "Late",
    "early_departure": "Early departure",
    "absence": "Absence",
    "present": "Present",
    "absent": "Absent",
    "on_leave": "On leave",
    "remote": "Remote",
    "business_trip": "Business trip",
    "attendance_history": "Attendance history",
    "today_attendance": "Today's attendance",
    "monthly_summary": "Monthly summary",
    "weekly_summary": "Weekly summary",
    "face_recognition": "Face recognition",
    "manual_entry": "Manual entry",
    "location": "Location",
    "device": "Device",
    "already_checked_in": "You have already checked in today",
    "already_checked_out": "You have already checked out today",
    "must_check_in_first": "You must check in first",
    "please_wait": "Please wait a few seconds",
    "pointage_success": "Attendance recorded successfully",
    "pointage_error": "Error recording attendance",
    
    // Congés / Leaves
    "leave_request": "Leave request",
    "leave_type": "Leave type",
    "start_date": "Start date",
    "end_date": "End date",
    "duration": "Duration",
    "days": "days",
    "half_day": "Half day",
    "full_day": "Full day",
    "reason": "Reason",
    "balance": "Balance",
    "remaining_days": "Remaining days",
    "used_days": "Used days",
    "annual_leave": "Annual leave",
    "sick_leave": "Sick leave",
    "unpaid_leave": "Unpaid leave",
    "maternity_leave": "Maternity leave",
    "paternity_leave": "Paternity leave",
    "bereavement_leave": "Bereavement leave",
    "special_leave": "Special leave",
    "pending_requests": "Pending requests",
    "approved_requests": "Approved requests",
    "rejected_requests": "Rejected requests",
    "approve": "Approve",
    "reject": "Reject",
    "request_leave": "Request leave",
    "cancel_request": "Cancel request",
    "leave_calendar": "Leave calendar",
    "team_calendar": "Team calendar",
    
    // Documents / Contracts
    "document": "Document",
    "contract": "Contract",
    "file": "File",
    "files": "Files",
    "upload_file": "Upload file",
    "download_file": "Download file",
    "file_name": "File name",
    "file_type": "File type",
    "file_size": "File size",
    "upload_date": "Upload date",
    "contract_type": "Contract type",
    "cdi": "Permanent",
    "cdd": "Fixed-term",
    "stage": "Internship",
    "freelance": "Freelance",
    "sign_contract": "Sign contract",
    "signature": "Signature",
    "draw_signature": "Draw your signature",
    "clear_signature": "Clear signature",
    "signed_on": "Signed on",
    "sent_for_signature": "Sent for signature",
    "pending_signature": "Pending signature",
    "contract_signed": "Contract signed",
    "contract_archived": "Contract archived",
    "view_document": "View document",
    "download_signed": "Download signed version",
    "pdf_preview": "PDF preview",
    
    // Notifications
    "mark_as_read": "Mark as read",
    "mark_all_read": "Mark all as read",
    "unread": "Unread",
    "read": "Read",
    "new_notification": "New notification",
    "no_notifications": "No notifications",
    "notification_settings": "Notification settings",
    "email_me_when": "Email me when",
    "push_notify_when": "Push notify when",
    "high_priority": "High priority",
    "normal_priority": "Normal priority",
    "low_priority": "Low priority",
    
    // Auth
    "sign_in": "Sign in",
    "sign_up": "Sign up",
    "sign_out": "Sign out",
    "forgot_password": "Forgot password?",
    "reset_password": "Reset password",
    "remember_me": "Remember me",
    "verification_code": "Verification code",
    "enter_code": "Enter code",
    "send_code": "Send code",
    "resend_code": "Resend code",
    "verify": "Verify",
    "otp_sent": "Code sent to your email",
    "invalid_credentials": "Invalid credentials",
    "account_locked": "Account locked",
    "account_suspended": "Account suspended",
    "session_expired": "Session expired",
    "two_factor": "Two-factor authentication",
    "enable_2fa": "Enable 2FA",
    "disable_2fa": "Disable 2FA",
    
    // Errors
    "error_occurred": "An error occurred",
    "try_again": "Try again",
    "page_not_found": "Page not found",
    "access_denied": "Access denied",
    "unauthorized": "Unauthorized",
    "forbidden": "Forbidden",
    "internal_error": "Internal server error",
    "network_error": "Network error",
    "timeout_error": "Request timeout",
    "validation_error": "Validation error",
    "required_field": "This field is required",
    "invalid_email": "Invalid email",
    "invalid_phone": "Invalid phone number",
    "password_too_short": "Password too short",
    "passwords_dont_match": "Passwords don't match",
    "invalid_date": "Invalid date",
    "file_too_large": "File too large",
    "invalid_file_type": "Invalid file type",
    
    // Success messages
    "saved_successfully": "Saved successfully",
    "deleted_successfully": "Deleted successfully",
    "updated_successfully": "Updated successfully",
    "created_successfully": "Created successfully",
    "submitted_successfully": "Submitted successfully",
    "uploaded_successfully": "Uploaded successfully",
    "sent_successfully": "Sent successfully",
    "copied_to_clipboard": "Copied to clipboard",
    
    // Confirmations
    "confirm_delete": "Are you sure you want to delete?",
    "confirm_cancel": "Are you sure you want to cancel?",
    "confirm_logout": "Are you sure you want to logout?",
    "confirm_action": "Are you sure you want to continue?",
    "unsaved_changes": "You have unsaved changes",
    
    // Messages
    "welcome": "Welcome",
    "goodbye": "Goodbye",
    "no_data": "No data available",
    "no_results": "No results found",
    "loading_data": "Loading data...",
    "processing": "Processing...",
    "please_wait_processing": "Please wait, processing...",
    
    // Dashboard
    "total_employees": "Total employees",
    "present_today": "Present today",
    "on_leave_today": "On leave today",
    "pending_validations": "Pending validations",
    "recent_activities": "Recent activities",
    "quick_actions": "Quick actions",
    "statistics": "Statistics",
    "overview": "Overview",
    "analytics": "Analytics",
    "reports": "Reports",
    
    // Help
    "faq": "FAQ",
    "contact_support": "Contact support",
    "send_message": "Send message",
    "need_help": "Need help?",
  },
  ar: {
    // Common
    "dashboard": "لوحة التحكم",
    "home": "الرئيسية",
    "workspace": "مساحة العمل",
    "settings": "الإعدادات",
    "profile": "الملف الشخصي",
    "logout": "تسجيل الخروج",
    "login": "تسجيل الدخول",
    "save": "حفظ",
    "cancel": "إلغاء",
    "delete": "حذف",
    "edit": "تعديل",
    "add": "إضافة",
    "search": "بحث",
    "loading": "جاري التحميل...",
    "error": "خطأ",
    "success": "نجاح",
    "confirm": "تأكيد",
    "close": "إغلاق",
    "back": "رجوع",
    "next": "التالي",
    "previous": "السابق",
    "submit": "إرسال",
    "reset": "إعادة تعيين",
    "clear": "مسح",
    "view": "عرض",
    "download": "تحميل",
    "upload": "رفع",
    "refresh": "تحديث",
    "filter": "تصفية",
    "export": "تصدير",
    "import": "استيراد",
    "print": "طباعة",
    "copy": "نسخ",
    "select": "اختيار",
    "select_all": "تحديد الكل",
    "deselect_all": "إلغاء تحديد الكل",
    "yes": "نعم",
    "no": "لا",
    "or": "أو",
    "and": "و",
    "optional": "اختياري",
    "required": "مطلوب",
    "actions": "إجراءات",
    "details": "تفاصيل",
    "description": "الوصف",
    "date": "التاريخ",
    "time": "الوقت",
    "status": "الحالة",
    "type": "النوع",
    "name": "الاسم",
    "title": "العنوان",
    "message": "رسالة",
    "comment": "تعليق",
    "notes": "ملاحظات",
    "created_at": "تاريخ الإنشاء",
    "updated_at": "تاريخ التحديث",
    "created_by": "أنشئ بواسطة",
    "all": "الكل",
    "none": "لا شيء",
    "today": "اليوم",
    "yesterday": "أمس",
    "this_week": "هذا الأسبوع",
    "this_month": "هذا الشهر",
    "this_year": "هذه السنة",
    
    // Navigation / Sidebar
    "employees": "الموظفون",
    "attendance": "الحضور",
    "leaves": "الإجازات",
    "documents": "المستندات",
    "contracts": "العقود",
    "ai_assistant": "المساعد الذكي",
    "hr": "الموارد البشرية",
    "notifications": "الإشعارات",
    "my_documents": "مستنداتي",
    "leave_requests": "طلبات الإجازة",
    "leave_management": "إدارة الإجازات",
    "notification_center": "مركز الإشعارات",
    "user_management": "إدارة المستخدمين",
    "role_management": "إدارة الأدوار",
    "help": "المساعدة",
    "audit_logs": "سجل التدقيق",
    "cookie_settings": "إعدادات ملفات تعريف الارتباط",
    "administration": "الإدارة",
    "profile_validation": "التحقق من الملفات الشخصية",
    "login_history": "سجل تسجيل الدخول",
    "public_holidays": "العطل الرسمية",
    "manage_holidays_desc": "إدارة العطل الرسمية الوطنية والدينية",
    "add_holiday": "إضافة عطلة",
    "edit_holiday": "تعديل العطلة",
    "holiday_name": "اسم العطلة",
    "holiday_name_placeholder": "مثال: عيد الاستقلال",
    "holiday_description_placeholder": "الوصف أو الملاحظات...",
    "national": "وطني",
    "religious": "ديني",
    "national_holidays": "العطل الوطنية",
    "religious_holidays": "العطل الدينية",
    "total_holidays": "إجمالي العطل",
    "paid_holidays": "العطل المدفوعة",
    "paid": "مدفوع",
    "unpaid": "غير مدفوع",
    "paid_holiday": "عطلة مدفوعة",
    "paid_holiday_desc": "هذه العطلة مدفوعة الأجر",
    "unpaid_holiday_desc": "هذه العطلة غير مدفوعة الأجر",
    "fixed_date": "تاريخ ثابت كل سنة",
    "fixed_date_desc": "التاريخ لا يتغير من سنة لأخرى",
    "variable_date_desc": "التاريخ يتغير كل سنة (مثل الأعياد الدينية)",
    "date_changes": "تاريخ متغير",
    "variable_date": "تاريخ متغير",
    "fixed_short": "ثابت",
    "variable_short": "متغير",
    "day_name": "اليوم",
    "holidays_list": "قائمة العطل",
    "no_holidays": "لا توجد عطل",
    "no_holidays_desc": "لم يتم تكوين أي عطلة لهذه السنة",
    "duplicate_year": "تكرار السنة",
    "duplicate_holidays": "تكرار العطل",
    "duplicate_holidays_desc": "انسخ العطل المتكررة من سنة إلى أخرى. سيتم نسخ العطل الدينية مع تذكير بالتحقق من التاريخ.",
    "from_year": "السنة المصدر",
    "to_year": "السنة الهدف",
    "duplicate": "تكرار",
    "duplicate_warning": "العطل الدينية لها تواريخ متغيرة. تذكر التحقق من التواريخ وتعديلها بعد التكرار.",
    "confirm_delete_holiday_desc": "هل أنت متأكد أنك تريد حذف هذه العطلة؟ لا يمكن التراجع عن هذا الإجراء.",
    "holiday_created_success": "تم إنشاء العطلة بنجاح",
    "holiday_updated_success": "تم تحديث العطلة بنجاح",
    "holiday_deleted_success": "تم حذف العطلة بنجاح",
    "error_loading_holidays": "خطأ في تحميل العطل",
    "religious_holiday_warning_title": "عطلة دينية بتاريخ متغير",
    "religious_holiday_warning_desc": "يتغير تاريخ هذه العطلة الدينية كل سنة. تذكر تحديثه سنوياً.",
    "list": "قائمة",
    "my_profile": "ملفي الشخصي",
    "my_attendance": "حضوري",
    "my_leaves": "إجازاتي",
    "my_contracts": "عقودي",
    "admin": "المشرف",
    "super_admin": "المشرف العام",
    
    // Settings
    "general": "عام",
    "security": "الأمان",
    "appearance": "المظهر",
    "devices": "الأجهزة",
    "language": "اللغة",
    "theme": "السمة",
    "dark_mode": "الوضع الداكن",
    "light_mode": "الوضع الفاتح",
    "system": "النظام",
    "notifications_settings": "إعدادات الإشعارات",
    "email_notifications": "إشعارات البريد الإلكتروني",
    "push_notifications": "الإشعارات الفورية",
    "privacy": "الخصوصية",
    
    // User / Profile
    "first_name": "الاسم الأول",
    "last_name": "اسم العائلة",
    "email": "البريد الإلكتروني",
    "phone": "الهاتف",
    "password": "كلمة المرور",
    "change_password": "تغيير كلمة المرور",
    "current_password": "كلمة المرور الحالية",
    "new_password": "كلمة المرور الجديدة",
    "confirm_password": "تأكيد كلمة المرور",
    "address": "العنوان",
    "city": "المدينة",
    "country": "البلد",
    "postal_code": "الرمز البريدي",
    "date_of_birth": "تاريخ الميلاد",
    "gender": "الجنس",
    "male": "ذكر",
    "female": "أنثى",
    "other": "آخر",
    "department": "القسم",
    "position": "المنصب",
    "hire_date": "تاريخ التوظيف",
    "employee_id": "رقم الموظف",
    "manager": "المدير",
    "team": "الفريق",
    "avatar": "صورة الملف الشخصي",
    "change_avatar": "تغيير الصورة",
    "role": "الدور",
    "user": "مستخدم",
    
    // Status
    "active": "نشط",
    "inactive": "غير نشط",
    "pending": "قيد الانتظار",
    "approved": "معتمد",
    "rejected": "مرفوض",
    "suspended": "معلق",
    "archived": "مؤرشف",
    "draft": "مسودة",
    "sent": "مرسل",
    "viewed": "تمت المشاهدة",
    "signed": "موقع",
    "cancelled": "ملغى",
    "completed": "مكتمل",
    "in_progress": "قيد التنفيذ",
    "expired": "منتهي الصلاحية",
    "valid": "صالح",
    "invalid": "غير صالح",
    "online": "متصل",
    "offline": "غير متصل",
    
    // Pointage / Attendance
    "check_in": "تسجيل الحضور",
    "check_out": "تسجيل الانصراف",
    "checked_in": "تم تسجيل الحضور",
    "checked_out": "تم تسجيل الانصراف",
    "check_in_time": "وقت الحضور",
    "check_out_time": "وقت الانصراف",
    "working_hours": "ساعات العمل",
    "overtime": "ساعات إضافية",
    "late": "تأخير",
    "early_departure": "انصراف مبكر",
    "absence": "غياب",
    "present": "حاضر",
    "absent": "غائب",
    "on_leave": "في إجازة",
    "remote": "عمل عن بُعد",
    "business_trip": "رحلة عمل",
    "attendance_history": "سجل الحضور",
    "today_attendance": "حضور اليوم",
    "monthly_summary": "الملخص الشهري",
    "weekly_summary": "الملخص الأسبوعي",
    "face_recognition": "التعرف على الوجه",
    "manual_entry": "إدخال يدوي",
    "location": "الموقع",
    "device": "الجهاز",
    "already_checked_in": "لقد سجلت حضورك بالفعل اليوم",
    "already_checked_out": "لقد سجلت انصرافك بالفعل اليوم",
    "must_check_in_first": "يجب تسجيل الحضور أولاً",
    "please_wait": "يرجى الانتظار بضع ثوانٍ",
    "pointage_success": "تم تسجيل الحضور بنجاح",
    "pointage_error": "خطأ في تسجيل الحضور",
    
    // Congés / Leaves
    "leave_request": "طلب إجازة",
    "leave_type": "نوع الإجازة",
    "start_date": "تاريخ البدء",
    "end_date": "تاريخ الانتهاء",
    "duration": "المدة",
    "days": "أيام",
    "half_day": "نصف يوم",
    "full_day": "يوم كامل",
    "reason": "السبب",
    "balance": "الرصيد",
    "remaining_days": "الأيام المتبقية",
    "used_days": "الأيام المستخدمة",
    "annual_leave": "إجازة سنوية",
    "sick_leave": "إجازة مرضية",
    "unpaid_leave": "إجازة بدون راتب",
    "maternity_leave": "إجازة أمومة",
    "paternity_leave": "إجازة أبوة",
    "bereavement_leave": "إجازة وفاة",
    "special_leave": "إجازة خاصة",
    "pending_requests": "الطلبات المعلقة",
    "approved_requests": "الطلبات المعتمدة",
    "rejected_requests": "الطلبات المرفوضة",
    "approve": "اعتماد",
    "reject": "رفض",
    "request_leave": "طلب إجازة",
    "cancel_request": "إلغاء الطلب",
    "leave_calendar": "تقويم الإجازات",
    "team_calendar": "تقويم الفريق",
    
    // Documents / Contracts
    "document": "مستند",
    "contract": "عقد",
    "file": "ملف",
    "files": "ملفات",
    "upload_file": "رفع ملف",
    "download_file": "تحميل الملف",
    "file_name": "اسم الملف",
    "file_type": "نوع الملف",
    "file_size": "حجم الملف",
    "upload_date": "تاريخ الرفع",
    "contract_type": "نوع العقد",
    "cdi": "عقد دائم",
    "cdd": "عقد محدد المدة",
    "stage": "تدريب",
    "freelance": "عمل حر",
    "sign_contract": "توقيع العقد",
    "signature": "التوقيع",
    "draw_signature": "ارسم توقيعك",
    "clear_signature": "مسح التوقيع",
    "signed_on": "تم التوقيع في",
    "sent_for_signature": "أُرسل للتوقيع",
    "pending_signature": "في انتظار التوقيع",
    "contract_signed": "تم توقيع العقد",
    "contract_archived": "تم أرشفة العقد",
    "view_document": "عرض المستند",
    "download_signed": "تحميل النسخة الموقعة",
    "pdf_preview": "معاينة PDF",
    
    // Notifications
    "mark_as_read": "تحديد كمقروء",
    "mark_all_read": "تحديد الكل كمقروء",
    "unread": "غير مقروء",
    "read": "مقروء",
    "new_notification": "إشعار جديد",
    "no_notifications": "لا توجد إشعارات",
    "notification_settings": "إعدادات الإشعارات",
    "email_me_when": "أرسل لي بريدًا عندما",
    "push_notify_when": "إشعار فوري عندما",
    "high_priority": "أولوية عالية",
    "normal_priority": "أولوية عادية",
    "low_priority": "أولوية منخفضة",
    
    // Auth
    "sign_in": "تسجيل الدخول",
    "sign_up": "إنشاء حساب",
    "sign_out": "تسجيل الخروج",
    "forgot_password": "نسيت كلمة المرور؟",
    "reset_password": "إعادة تعيين كلمة المرور",
    "remember_me": "تذكرني",
    "verification_code": "رمز التحقق",
    "enter_code": "أدخل الرمز",
    "send_code": "إرسال الرمز",
    "resend_code": "إعادة إرسال الرمز",
    "verify": "تحقق",
    "otp_sent": "تم إرسال الرمز إلى بريدك الإلكتروني",
    "invalid_credentials": "بيانات الدخول غير صحيحة",
    "account_locked": "الحساب مقفل",
    "account_suspended": "الحساب معلق",
    "session_expired": "انتهت صلاحية الجلسة",
    "two_factor": "المصادقة الثنائية",
    "enable_2fa": "تفعيل المصادقة الثنائية",
    "disable_2fa": "تعطيل المصادقة الثنائية",
    
    // Errors
    "error_occurred": "حدث خطأ",
    "try_again": "حاول مرة أخرى",
    "page_not_found": "الصفحة غير موجودة",
    "access_denied": "تم رفض الوصول",
    "unauthorized": "غير مصرح",
    "forbidden": "محظور",
    "internal_error": "خطأ في الخادم",
    "network_error": "خطأ في الشبكة",
    "timeout_error": "انتهى وقت الطلب",
    "validation_error": "خطأ في التحقق",
    "required_field": "هذا الحقل مطلوب",
    "invalid_email": "بريد إلكتروني غير صالح",
    "invalid_phone": "رقم هاتف غير صالح",
    "password_too_short": "كلمة المرور قصيرة جدًا",
    "passwords_dont_match": "كلمات المرور غير متطابقة",
    "invalid_date": "تاريخ غير صالح",
    "file_too_large": "الملف كبير جدًا",
    "invalid_file_type": "نوع ملف غير صالح",
    
    // Success messages
    "saved_successfully": "تم الحفظ بنجاح",
    "deleted_successfully": "تم الحذف بنجاح",
    "updated_successfully": "تم التحديث بنجاح",
    "created_successfully": "تم الإنشاء بنجاح",
    "submitted_successfully": "تم الإرسال بنجاح",
    "uploaded_successfully": "تم الرفع بنجاح",
    "sent_successfully": "تم الإرسال بنجاح",
    "copied_to_clipboard": "تم النسخ إلى الحافظة",
    
    // Confirmations
    "confirm_delete": "هل أنت متأكد من الحذف؟",
    "confirm_cancel": "هل أنت متأكد من الإلغاء؟",
    "confirm_logout": "هل أنت متأكد من تسجيل الخروج؟",
    "confirm_action": "هل أنت متأكد من المتابعة؟",
    "unsaved_changes": "لديك تغييرات غير محفوظة",
    
    // Messages
    "welcome": "مرحبا",
    "goodbye": "وداعا",
    "no_data": "لا توجد بيانات متاحة",
    "no_results": "لم يتم العثور على نتائج",
    "loading_data": "جاري تحميل البيانات...",
    "processing": "جاري المعالجة...",
    "please_wait_processing": "يرجى الانتظار، جاري المعالجة...",
    
    // Dashboard
    "total_employees": "إجمالي الموظفين",
    "present_today": "الحاضرون اليوم",
    "on_leave_today": "في إجازة اليوم",
    "pending_validations": "التحققات المعلقة",
    "recent_activities": "الأنشطة الأخيرة",
    "quick_actions": "إجراءات سريعة",
    "statistics": "الإحصائيات",
    "overview": "نظرة عامة",
    "analytics": "التحليلات",
    "reports": "التقارير",
    
    // Help
    "faq": "الأسئلة الشائعة",
    "contact_support": "الاتصال بالدعم",
    "send_message": "إرسال رسالة",
    "need_help": "هل تحتاج مساعدة؟",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const { data: session } = useSession();
  const [language, setLanguageState] = useState<Language>("fr");
  const [isLoaded, setIsLoaded] = useState(false);

  // Load language from localStorage or DB on mount
  useEffect(() => {
    const loadLanguage = async () => {
      // First check localStorage
      const storedLang = localStorage.getItem("language") as Language;
      if (storedLang && ["fr", "en", "ar"].includes(storedLang)) {
        setLanguageState(storedLang);
      }

      // If logged in, try to fetch from DB
      if (session?.user?.id) {
        try {
          const res = await fetch("/api/users/preferences");
          if (res.ok) {
            const data = await res.json();
            if (data.preferences?.language) {
              const dbLang = data.preferences.language as Language;
              setLanguageState(dbLang);
              localStorage.setItem("language", dbLang);
            }
          }
        } catch (error) {
          console.error("Failed to fetch language preference:", error);
        }
      }
      
      setIsLoaded(true);
    };

    loadLanguage();
  }, [session?.user?.id]);

  // Apply RTL direction to document
  useEffect(() => {
    if (isLoaded) {
      document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
      document.documentElement.lang = language;
    }
  }, [language, isLoaded]);

  const setLanguage = async (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
    
    // Update document direction
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = lang;

    // Save to DB if logged in
    if (session?.user?.id) {
      try {
        await fetch("/api/users/preferences", {
          method: "PUT",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ key: "language", value: lang }),
        });
      } catch (error) {
        console.error("Failed to save language preference:", error);
      }
    }
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const isRTL = language === "ar";

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
